server:
  port: 8040
  # 应用名称 （nacos会将该名称当做服务名称）
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 192.168.10.2:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
# springboot默认的日志级别是info ,feign的dubug日志级别就不会输入
logging:
  level:
    com.tulingxueyuan.order.feign: debug
# feign日志局部配置
feign:
  client:
    config:
      #服务名
      product-service:
        loggerLevel: BASIC
        contract: feign.Contract.Default #设置为默认的契约  （还原成原生注解）
        # 连接超时时间，默认2s
        connectTimeout: 5000
        # 请求处理超时时间，默认5s
#        readTimeout: 3000
        readTimeout: 10000
        request-interceptors:
          - com.tulingxueyuan.order.intercptor.feign.CustomFeignInterceptor
          - com.tulingxueyuan.order.intercptor.feign.FeignAuthRequestInterceptor
